# Add configuration values here, as shown below.
#

YELP_CONSUMER_KEY: hCTaBcVlgZ17kGVkIkjxKg
YELP_CONSUMER_SECRET: sIjr5P755ai8DaEE-2oEtRWSpm8
YELP_TOKEN: gH6cLOJ2odvCGWZdakD1LSWk0eUHXx-9
YELP_TOKEN_SECRET: w7fEB66UVXg_DujeiF6VmdRr0iE

# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
