# Add configuration values here, as shown below.
#
yelp_consumer_key: hCTaBcVlgZ17kGVkIkjxKg
yelp_consumer_secret: sIjr5P755ai8DaEE-2oEtRWSpm8
yelp_token: qCUzEyLgA_XmZl0wxSVvRkjXBfFRgisr
yelp_token_secret: m-QKLTpR9QopbhUQRU_6R2sorFA

# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
